language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: true

env:
  global:
    - DOCUMENTER_DEBUG=true

script:
  - julia -e 'using Pkg; Pkg.build()'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
