language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.2
  - 1.3

matrix:
  allow_failures:
    - julia: 1.3

notifications:
  email: true

env:
  global:
    - DOCUMENTER_DEBUG=true

script:
  - julia --color=yes -e 'using Pkg; Pkg.build()'
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'import Pkg; Pkg.add("Documenter")'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - julia -e 'cd(Pkg.dir("IntegerSequences.jl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
